Fix initial guess to be within bounds
The initial guess for the higher dimensional search could fall outside
of the parameter bounds. This was causing the error
```
ValueError: `x0` violates bound constraints.
```
by fmin_tnc() in integration tests of param_search.

This commit forces the initial guess to be within the parameter bounds.